### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by computerwizjared** [Radirius/Mercury#15]
Is there a Maven repository that I can use?

**Comment by cebarks** [comment]
Here is one I set up: http://dev.cebarks.net/nexus/content/repositories/cebarks/
It's auto-updated using Jenkins at http://dev.cebarks.net/jenkins/job/Mercury/

**Comment by Jeviny** [comment]
http://repo.radiri.us/com/radirius/mercury/Mercury/

Here ya go.

**Comment by computerwizjared** [comment]
Thank you! This is awesome!
