### ISSUE TITLE
LWJGL 3 Support

### ISSUE THREAD

**Issue by cebarks** [Radirius/Mercury#16]
Has there been any talk or a plan to either add support for or move to LWJGL 3?

EDIT: When there is an official stable release of course.

**Comment by wessles** [comment]
We will have an official release soon.

**Comment by cebarks** [comment]
I meant an official release of LWJGL 3

**Comment by sriharshachilakapati** [comment]
In the current state, LWJGL3 is still buggy, there are AWT/GLFW issues on Mac OS, which prevents some features of Mercury from working on Mac. Though there are fixes or workarounds, they are quite hackish at the moment, so it is better to wait for the official release.
