### ISSUE TITLE
Wiki tutorials are missing a lot of features

### ISSUE THREAD

**Issue by maolivo** [Radirius/Mercury#22]
I don't think this qualifies as an actual "issue", but I figured this might be the easiest way to communicate to the project as a whole. I'm going to be using Mercury in my AP Computer Science as a post-AP project for my students. To help facilitate this, I'm going to be referencing the wiki tutorials a fair amount as reminders of how to do things.

As I looked at them, I noticed that there are some features that exist in the library that are not documented on the wiki, such as fonts. I planned on adding additional pages for some of these features that are no documented, but I mainly wanted to get the "OK" from you guys, as well as any specifics on how you like the wiki tutorial pages set up.

Thanks!

**Comment by Jeviny** [comment]
> 'I planned on adding additional pages for some of these features that are no documented, but I mainly wanted to get the "OK" from you guys, as well as any specifics on how you like the wiki tutorial pages set up.'

If you want to modify the wiki, go right ahead! You'll probably get a good gist of how the page layout for most articles is after browsing around.

The only tip I can give you, if you decide to contribute to the wiki, is to use a lot of images. Screencaps and animated GIFs of each feature are really helpful.

Cheers!
