### ISSUE TITLE
Database errors on the Mercury forum

### ISSUE THREAD

**Issue by sriharshachilakapati** [Radirius/Mercury#25]
I've been watching the forum (http://mercurylib.com/forum/) and it is saying that it had errors connecting to the database since the last two days.

> Connection Problems
> ----
>
> Sorry, SMF was unable to connect to the database. This may be caused by the server being busy. 
> Please try again later.

That is the message I'm getting. Also, is the IRC abandoned? I can find no one in #Mercury on Espernet.

**Comment by Jeviny** [comment]
Oh, yes. This is because we recently switched to another server. I'll see what I can do tonight to get things back up and running.
