### ISSUE TITLE
SpriteSheet class is not loading the spritesheet image! 

### ISSUE THREAD

**Issue by death-angel** [Radirius/Mercury#26]
I tried to load a spritesheet with the SpriteSheet class, everything is right until i print the subtextures length and i get 0... 
And if i try to get a subtexture[0] i get an ArrayOutOfBounds exception.

**Comment by Jeviny** [comment]
Can we get some code snippets?

**Comment by death-angel** [comment]
this is my code http://pastebin.com/hnLTfqki

**Comment by death-angel** [comment]
So the integer tank_height is 532 but the texture only has 432. I fix it and now it works but i think the LoadSpriteSheet method should verify if the width or height is bigger than the texture width or height .
